# fly.toml app configuration file generated for opensolano-staging on 2025-09-05T12:59:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opensolano-staging'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  JEKYLL_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    soft_limit = 25
    hard_limit = 50

[checks]
  [checks.http]
    port = 8080
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/'
    headers = { "X-Health-Check" = "1" }
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
